/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubwayRouteImport } from './routes/subway'
import { Route as ShuttleRouteImport } from './routes/shuttle'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSubwayPreviewRouteImport } from './routes/api/subway/preview'
import { Route as ApiSubwayArrivalRouteImport } from './routes/api/subway/arrival'
import { Route as ApiShuttleTimeTableRulesRouteImport } from './routes/api/shuttle/time-table-rules'
import { Route as ApiShuttlePatternsRouteImport } from './routes/api/shuttle/patterns'
import { Route as ApiShuttleV2TimesRouteImport } from './routes/api/shuttle/v2/times'
import { Route as ApiShuttleV2StopsRouteImport } from './routes/api/shuttle/v2/stops'

const SubwayRoute = SubwayRouteImport.update({
  id: '/subway',
  path: '/subway',
  getParentRoute: () => rootRouteImport,
} as any)
const ShuttleRoute = ShuttleRouteImport.update({
  id: '/shuttle',
  path: '/shuttle',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubwayPreviewRoute = ApiSubwayPreviewRouteImport.update({
  id: '/api/subway/preview',
  path: '/api/subway/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubwayArrivalRoute = ApiSubwayArrivalRouteImport.update({
  id: '/api/subway/arrival',
  path: '/api/subway/arrival',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShuttleTimeTableRulesRoute =
  ApiShuttleTimeTableRulesRouteImport.update({
    id: '/api/shuttle/time-table-rules',
    path: '/api/shuttle/time-table-rules',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiShuttlePatternsRoute = ApiShuttlePatternsRouteImport.update({
  id: '/api/shuttle/patterns',
  path: '/api/shuttle/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShuttleV2TimesRoute = ApiShuttleV2TimesRouteImport.update({
  id: '/api/shuttle/v2/times',
  path: '/api/shuttle/v2/times',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShuttleV2StopsRoute = ApiShuttleV2StopsRouteImport.update({
  id: '/api/shuttle/v2/stops',
  path: '/api/shuttle/v2/stops',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/shuttle': typeof ShuttleRoute
  '/subway': typeof SubwayRoute
  '/api/shuttle/patterns': typeof ApiShuttlePatternsRoute
  '/api/shuttle/time-table-rules': typeof ApiShuttleTimeTableRulesRoute
  '/api/subway/arrival': typeof ApiSubwayArrivalRoute
  '/api/subway/preview': typeof ApiSubwayPreviewRoute
  '/api/shuttle/v2/stops': typeof ApiShuttleV2StopsRoute
  '/api/shuttle/v2/times': typeof ApiShuttleV2TimesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/shuttle': typeof ShuttleRoute
  '/subway': typeof SubwayRoute
  '/api/shuttle/patterns': typeof ApiShuttlePatternsRoute
  '/api/shuttle/time-table-rules': typeof ApiShuttleTimeTableRulesRoute
  '/api/subway/arrival': typeof ApiSubwayArrivalRoute
  '/api/subway/preview': typeof ApiSubwayPreviewRoute
  '/api/shuttle/v2/stops': typeof ApiShuttleV2StopsRoute
  '/api/shuttle/v2/times': typeof ApiShuttleV2TimesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/shuttle': typeof ShuttleRoute
  '/subway': typeof SubwayRoute
  '/api/shuttle/patterns': typeof ApiShuttlePatternsRoute
  '/api/shuttle/time-table-rules': typeof ApiShuttleTimeTableRulesRoute
  '/api/subway/arrival': typeof ApiSubwayArrivalRoute
  '/api/subway/preview': typeof ApiSubwayPreviewRoute
  '/api/shuttle/v2/stops': typeof ApiShuttleV2StopsRoute
  '/api/shuttle/v2/times': typeof ApiShuttleV2TimesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/shuttle'
    | '/subway'
    | '/api/shuttle/patterns'
    | '/api/shuttle/time-table-rules'
    | '/api/subway/arrival'
    | '/api/subway/preview'
    | '/api/shuttle/v2/stops'
    | '/api/shuttle/v2/times'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/shuttle'
    | '/subway'
    | '/api/shuttle/patterns'
    | '/api/shuttle/time-table-rules'
    | '/api/subway/arrival'
    | '/api/subway/preview'
    | '/api/shuttle/v2/stops'
    | '/api/shuttle/v2/times'
  id:
    | '__root__'
    | '/'
    | '/shuttle'
    | '/subway'
    | '/api/shuttle/patterns'
    | '/api/shuttle/time-table-rules'
    | '/api/subway/arrival'
    | '/api/subway/preview'
    | '/api/shuttle/v2/stops'
    | '/api/shuttle/v2/times'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShuttleRoute: typeof ShuttleRoute
  SubwayRoute: typeof SubwayRoute
  ApiShuttlePatternsRoute: typeof ApiShuttlePatternsRoute
  ApiShuttleTimeTableRulesRoute: typeof ApiShuttleTimeTableRulesRoute
  ApiSubwayArrivalRoute: typeof ApiSubwayArrivalRoute
  ApiSubwayPreviewRoute: typeof ApiSubwayPreviewRoute
  ApiShuttleV2StopsRoute: typeof ApiShuttleV2StopsRoute
  ApiShuttleV2TimesRoute: typeof ApiShuttleV2TimesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subway': {
      id: '/subway'
      path: '/subway'
      fullPath: '/subway'
      preLoaderRoute: typeof SubwayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shuttle': {
      id: '/shuttle'
      path: '/shuttle'
      fullPath: '/shuttle'
      preLoaderRoute: typeof ShuttleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subway/preview': {
      id: '/api/subway/preview'
      path: '/api/subway/preview'
      fullPath: '/api/subway/preview'
      preLoaderRoute: typeof ApiSubwayPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subway/arrival': {
      id: '/api/subway/arrival'
      path: '/api/subway/arrival'
      fullPath: '/api/subway/arrival'
      preLoaderRoute: typeof ApiSubwayArrivalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shuttle/time-table-rules': {
      id: '/api/shuttle/time-table-rules'
      path: '/api/shuttle/time-table-rules'
      fullPath: '/api/shuttle/time-table-rules'
      preLoaderRoute: typeof ApiShuttleTimeTableRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shuttle/patterns': {
      id: '/api/shuttle/patterns'
      path: '/api/shuttle/patterns'
      fullPath: '/api/shuttle/patterns'
      preLoaderRoute: typeof ApiShuttlePatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shuttle/v2/times': {
      id: '/api/shuttle/v2/times'
      path: '/api/shuttle/v2/times'
      fullPath: '/api/shuttle/v2/times'
      preLoaderRoute: typeof ApiShuttleV2TimesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shuttle/v2/stops': {
      id: '/api/shuttle/v2/stops'
      path: '/api/shuttle/v2/stops'
      fullPath: '/api/shuttle/v2/stops'
      preLoaderRoute: typeof ApiShuttleV2StopsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShuttleRoute: ShuttleRoute,
  SubwayRoute: SubwayRoute,
  ApiShuttlePatternsRoute: ApiShuttlePatternsRoute,
  ApiShuttleTimeTableRulesRoute: ApiShuttleTimeTableRulesRoute,
  ApiSubwayArrivalRoute: ApiSubwayArrivalRoute,
  ApiSubwayPreviewRoute: ApiSubwayPreviewRoute,
  ApiShuttleV2StopsRoute: ApiShuttleV2StopsRoute,
  ApiShuttleV2TimesRoute: ApiShuttleV2TimesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
