/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimetableRouteImport } from './routes/timetable'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiShuttleTimeTableRulesRouteImport } from './routes/api/shuttle/time-table-rules'
import { Route as ApiShuttlePatternsRouteImport } from './routes/api/shuttle/patterns'

const TimetableRoute = TimetableRouteImport.update({
  id: '/timetable',
  path: '/timetable',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShuttleTimeTableRulesRoute =
  ApiShuttleTimeTableRulesRouteImport.update({
    id: '/api/shuttle/time-table-rules',
    path: '/api/shuttle/time-table-rules',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiShuttlePatternsRoute = ApiShuttlePatternsRouteImport.update({
  id: '/api/shuttle/patterns',
  path: '/api/shuttle/patterns',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/timetable': typeof TimetableRoute
  '/api/shuttle/patterns': typeof ApiShuttlePatternsRoute
  '/api/shuttle/time-table-rules': typeof ApiShuttleTimeTableRulesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/timetable': typeof TimetableRoute
  '/api/shuttle/patterns': typeof ApiShuttlePatternsRoute
  '/api/shuttle/time-table-rules': typeof ApiShuttleTimeTableRulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/timetable': typeof TimetableRoute
  '/api/shuttle/patterns': typeof ApiShuttlePatternsRoute
  '/api/shuttle/time-table-rules': typeof ApiShuttleTimeTableRulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/timetable'
    | '/api/shuttle/patterns'
    | '/api/shuttle/time-table-rules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/timetable'
    | '/api/shuttle/patterns'
    | '/api/shuttle/time-table-rules'
  id:
    | '__root__'
    | '/'
    | '/timetable'
    | '/api/shuttle/patterns'
    | '/api/shuttle/time-table-rules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TimetableRoute: typeof TimetableRoute
  ApiShuttlePatternsRoute: typeof ApiShuttlePatternsRoute
  ApiShuttleTimeTableRulesRoute: typeof ApiShuttleTimeTableRulesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timetable': {
      id: '/timetable'
      path: '/timetable'
      fullPath: '/timetable'
      preLoaderRoute: typeof TimetableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shuttle/time-table-rules': {
      id: '/api/shuttle/time-table-rules'
      path: '/api/shuttle/time-table-rules'
      fullPath: '/api/shuttle/time-table-rules'
      preLoaderRoute: typeof ApiShuttleTimeTableRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shuttle/patterns': {
      id: '/api/shuttle/patterns'
      path: '/api/shuttle/patterns'
      fullPath: '/api/shuttle/patterns'
      preLoaderRoute: typeof ApiShuttlePatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TimetableRoute: TimetableRoute,
  ApiShuttlePatternsRoute: ApiShuttlePatternsRoute,
  ApiShuttleTimeTableRulesRoute: ApiShuttleTimeTableRulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
